# NodeJS Version 20
FROM node:20.11.1-buster-slim

RUN apt-get update -y && apt-get install -y openssl

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install Node Package
RUN npm install --legacy-peer-deps

# Set Env
ENV NODE_ENV production

EXPOSE 3000

# Cmd script
CMD ["npm", "run", "start"]
