version: "3.9"

services:
  proxy:
    container_name: proxy-lab-software-si7n-2024
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend

  server:
    container_name: server-lab-software-si7n-2024
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: mysql://root:password@mysql:3306/dev
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
      container_name: mysql-lab-software-si7n-2024
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: password

      ports:
        - "3306:3306"
      networks:
        - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
